// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN3Gz8vhpBXInhFnEeE_XuhuYHS78Z4FE',
    appId: '1:899451446208:web:8d3eb22d02657e75469e25',
    messagingSenderId: '899451446208',
    projectId: 'monix-zm',
    authDomain: 'monix-zm.firebaseapp.com',
    storageBucket: 'monix-zm.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqr96x7SQ0hIFlTomFONONl9o3JZU8jKA',
    appId: '1:899451446208:android:33f73ebc361aaed5469e25',
    messagingSenderId: '899451446208',
    projectId: 'monix-zm',
    storageBucket: 'monix-zm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3B28iYBdrQ-HjoXCPnfzlyuQ55FiPn9Q',
    appId: '1:899451446208:ios:922007ebcbc39030469e25',
    messagingSenderId: '899451446208',
    projectId: 'monix-zm',
    storageBucket: 'monix-zm.firebasestorage.app',
    iosBundleId: 'com.example.monixx',
  );
}
